kind: Deployment
apiVersion: apps/v1
metadata:
  name: kitex-service-a-default-prod
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/kitex-service-a-default-prod
  uid: 16343cec-a4df-4ed2-ac81-9c8f9001ed9e
  resourceVersion: '479049'
  generation: 14
  creationTimestamp: '2021-08-17T06:44:24Z'
  labels:
    appgroup: ''
    bytemesh.io.psm: kitex.service.a
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitex-service-a-default-prod
      bytemesh.io.psm: kitex.service.a
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kitex-service-a-default-prod
        bytemesh.io.psm: kitex.service.a
        version: v1
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
    spec:
      containers:
        - name: container-0
          image: 'swr.cn-north-4.myhuaweicloud.com/testwhn/service_a:latest'
          env:
            - name: PAAS_APP_NAME
              value: kitex-service-a-default-prod
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 0ac4457a7100102f2f11c01f7114e270
            - name: bearToken
              value: eyJhbGciOiJSUzI1NiIsImtpZCI6Im40bzJMMDNXNXBVLU95WlpfTnE1c3BYTnVHRlItcGJJdUxSMldNWWZqNjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJlbmRwb2ludC1jb250cm9sbGVyLXRva2VuLTU3cTZwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImVuZHBvaW50LWNvbnRyb2xsZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIzNmNmYWNiNS0yYmQ2LTQ4NDUtODZiMi02OGI5ODMzYTZjNWUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZW5kcG9pbnQtY29udHJvbGxlciJ9.XVGb0dpKZOXIb3mWuOKsFAjOF-fjcXOJgnQLnbq4V6otUD0lhg3lTAQtXf2wKNmPlpc2PQgUfcV1ITBvXS10mb1FSLbv10j5PuLeLIwXB7DlA8NilewgaMUTbrXhBqadGTPJOdzA2MLtlG8LnEbhpraPwfGXm19IAlk_mfiAhiQfEFQMVGkPl7F0D1EdFQGvof40e7vSLdMahyy510WfcteYQ8c4Sjmetm_dmAHv3skCZOPhbZ9CLBgpkEo7fYrFasiSpxnyGU0qMINNRgNl7Kd7Ykov2ODG81CKEBVPg9mgBhbwHzPmRX2IMUoMcY-vusIfqRkMZhix76a7-bqN6A
          resources:
            limits:
              cpu: '4'
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      dnsConfig:
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 14
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-08-17T06:44:25Z'
      lastTransitionTime: '2021-08-17T06:44:24Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "kitex-service-a-default-prod-58d86d9f5" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-08-17T07:54:33Z'
      lastTransitionTime: '2021-08-17T07:54:33Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
